package com.o2o.massage.dao.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table login_token
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class LoginToken {
    /**
     * Database Column Remarks:
     *   自增ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户唯一ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   设备ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.device_id
     *
     * @mbg.generated
     */
    private String deviceId;

    /**
     * Database Column Remarks:
     *   token信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.login_token
     *
     * @mbg.generated
     */
    private String loginToken;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   失效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_token.expire_time
     *
     * @mbg.generated
     */
    private Date expireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.id
     *
     * @return the value of login_token.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.id
     *
     * @param id the value for login_token.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.user_id
     *
     * @return the value of login_token.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.user_id
     *
     * @param userId the value for login_token.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.device_id
     *
     * @return the value of login_token.device_id
     *
     * @mbg.generated
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.device_id
     *
     * @param deviceId the value for login_token.device_id
     *
     * @mbg.generated
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.login_token
     *
     * @return the value of login_token.login_token
     *
     * @mbg.generated
     */
    public String getLoginToken() {
        return loginToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.login_token
     *
     * @param loginToken the value for login_token.login_token
     *
     * @mbg.generated
     */
    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken == null ? null : loginToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.create_time
     *
     * @return the value of login_token.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.create_time
     *
     * @param createTime the value for login_token.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_token.expire_time
     *
     * @return the value of login_token.expire_time
     *
     * @mbg.generated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_token.expire_time
     *
     * @param expireTime the value for login_token.expire_time
     *
     * @mbg.generated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }
}