package com.o2o.massage.dao.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table member_sympton
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MemberSympton {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.sympton_id
     *
     * @mbg.generated
     */
    private Long symptonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.customer_user_id
     *
     * @mbg.generated
     */
    private String customerUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.member_id
     *
     * @mbg.generated
     */
    private String memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.order_no
     *
     * @mbg.generated
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.upload
     *
     * @mbg.generated
     */
    private String upload;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_sympton.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.sympton_id
     *
     * @return the value of member_sympton.sympton_id
     *
     * @mbg.generated
     */
    public Long getSymptonId() {
        return symptonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.sympton_id
     *
     * @param symptonId the value for member_sympton.sympton_id
     *
     * @mbg.generated
     */
    public void setSymptonId(Long symptonId) {
        this.symptonId = symptonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.customer_user_id
     *
     * @return the value of member_sympton.customer_user_id
     *
     * @mbg.generated
     */
    public String getCustomerUserId() {
        return customerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.customer_user_id
     *
     * @param customerUserId the value for member_sympton.customer_user_id
     *
     * @mbg.generated
     */
    public void setCustomerUserId(String customerUserId) {
        this.customerUserId = customerUserId == null ? null : customerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.member_id
     *
     * @return the value of member_sympton.member_id
     *
     * @mbg.generated
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.member_id
     *
     * @param memberId the value for member_sympton.member_id
     *
     * @mbg.generated
     */
    public void setMemberId(String memberId) {
        this.memberId = memberId == null ? null : memberId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.order_no
     *
     * @return the value of member_sympton.order_no
     *
     * @mbg.generated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.order_no
     *
     * @param orderNo the value for member_sympton.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.desc
     *
     * @return the value of member_sympton.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.desc
     *
     * @param desc the value for member_sympton.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.upload
     *
     * @return the value of member_sympton.upload
     *
     * @mbg.generated
     */
    public String getUpload() {
        return upload;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.upload
     *
     * @param upload the value for member_sympton.upload
     *
     * @mbg.generated
     */
    public void setUpload(String upload) {
        this.upload = upload == null ? null : upload.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.create_by
     *
     * @return the value of member_sympton.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.create_by
     *
     * @param createBy the value for member_sympton.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.update_by
     *
     * @return the value of member_sympton.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.update_by
     *
     * @param updateBy the value for member_sympton.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.create_time
     *
     * @return the value of member_sympton.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.create_time
     *
     * @param createTime the value for member_sympton.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_sympton.update_time
     *
     * @return the value of member_sympton.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_sympton.update_time
     *
     * @param updateTime the value for member_sympton.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}