package com.o2o.massage.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_info
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public OrderInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("`order_id` is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("`order_id` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(Long value) {
            addCriterion("`order_id` =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(Long value) {
            addCriterion("`order_id` <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(Long value) {
            addCriterion("`order_id` >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`order_id` >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(Long value) {
            addCriterion("`order_id` <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(Long value) {
            addCriterion("`order_id` <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<Long> values) {
            addCriterion("`order_id` in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<Long> values) {
            addCriterion("`order_id` not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(Long value1, Long value2) {
            addCriterion("`order_id` between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(Long value1, Long value2) {
            addCriterion("`order_id` not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNull() {
            addCriterion("`order_no` is null");
            return (Criteria) this;
        }

        public Criteria andOrderNoIsNotNull() {
            addCriterion("`order_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNoEqualTo(String value) {
            addCriterion("`order_no` =", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotEqualTo(String value) {
            addCriterion("`order_no` <>", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThan(String value) {
            addCriterion("`order_no` >", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("`order_no` >=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThan(String value) {
            addCriterion("`order_no` <", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLessThanOrEqualTo(String value) {
            addCriterion("`order_no` <=", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoLike(String value) {
            addCriterion("`order_no` like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotLike(String value) {
            addCriterion("`order_no` not like", value, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoIn(List<String> values) {
            addCriterion("`order_no` in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotIn(List<String> values) {
            addCriterion("`order_no` not in", values, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoBetween(String value1, String value2) {
            addCriterion("`order_no` between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andOrderNoNotBetween(String value1, String value2) {
            addCriterion("`order_no` not between", value1, value2, "orderNo");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdIsNull() {
            addCriterion("`customer_user_id` is null");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdIsNotNull() {
            addCriterion("`customer_user_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdEqualTo(String value) {
            addCriterion("`customer_user_id` =", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotEqualTo(String value) {
            addCriterion("`customer_user_id` <>", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdGreaterThan(String value) {
            addCriterion("`customer_user_id` >", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`customer_user_id` >=", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdLessThan(String value) {
            addCriterion("`customer_user_id` <", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdLessThanOrEqualTo(String value) {
            addCriterion("`customer_user_id` <=", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdLike(String value) {
            addCriterion("`customer_user_id` like", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotLike(String value) {
            addCriterion("`customer_user_id` not like", value, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdIn(List<String> values) {
            addCriterion("`customer_user_id` in", values, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotIn(List<String> values) {
            addCriterion("`customer_user_id` not in", values, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdBetween(String value1, String value2) {
            addCriterion("`customer_user_id` between", value1, value2, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerUserIdNotBetween(String value1, String value2) {
            addCriterion("`customer_user_id` not between", value1, value2, "customerUserId");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("`customer_name` is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("`customer_name` is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("`customer_name` =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("`customer_name` <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("`customer_name` >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("`customer_name` >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("`customer_name` <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("`customer_name` <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("`customer_name` like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("`customer_name` not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("`customer_name` in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("`customer_name` not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("`customer_name` between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("`customer_name` not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdIsNull() {
            addCriterion("`provider_user_id` is null");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdIsNotNull() {
            addCriterion("`provider_user_id` is not null");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdEqualTo(String value) {
            addCriterion("`provider_user_id` =", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdNotEqualTo(String value) {
            addCriterion("`provider_user_id` <>", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdGreaterThan(String value) {
            addCriterion("`provider_user_id` >", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("`provider_user_id` >=", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdLessThan(String value) {
            addCriterion("`provider_user_id` <", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdLessThanOrEqualTo(String value) {
            addCriterion("`provider_user_id` <=", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdLike(String value) {
            addCriterion("`provider_user_id` like", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdNotLike(String value) {
            addCriterion("`provider_user_id` not like", value, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdIn(List<String> values) {
            addCriterion("`provider_user_id` in", values, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdNotIn(List<String> values) {
            addCriterion("`provider_user_id` not in", values, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdBetween(String value1, String value2) {
            addCriterion("`provider_user_id` between", value1, value2, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderUserIdNotBetween(String value1, String value2) {
            addCriterion("`provider_user_id` not between", value1, value2, "providerUserId");
            return (Criteria) this;
        }

        public Criteria andProviderNameIsNull() {
            addCriterion("`provider_name` is null");
            return (Criteria) this;
        }

        public Criteria andProviderNameIsNotNull() {
            addCriterion("`provider_name` is not null");
            return (Criteria) this;
        }

        public Criteria andProviderNameEqualTo(String value) {
            addCriterion("`provider_name` =", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameNotEqualTo(String value) {
            addCriterion("`provider_name` <>", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameGreaterThan(String value) {
            addCriterion("`provider_name` >", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameGreaterThanOrEqualTo(String value) {
            addCriterion("`provider_name` >=", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameLessThan(String value) {
            addCriterion("`provider_name` <", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameLessThanOrEqualTo(String value) {
            addCriterion("`provider_name` <=", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameLike(String value) {
            addCriterion("`provider_name` like", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameNotLike(String value) {
            addCriterion("`provider_name` not like", value, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameIn(List<String> values) {
            addCriterion("`provider_name` in", values, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameNotIn(List<String> values) {
            addCriterion("`provider_name` not in", values, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameBetween(String value1, String value2) {
            addCriterion("`provider_name` between", value1, value2, "providerName");
            return (Criteria) this;
        }

        public Criteria andProviderNameNotBetween(String value1, String value2) {
            addCriterion("`provider_name` not between", value1, value2, "providerName");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNull() {
            addCriterion("`member_id` is null");
            return (Criteria) this;
        }

        public Criteria andMemberIdIsNotNull() {
            addCriterion("`member_id` is not null");
            return (Criteria) this;
        }

        public Criteria andMemberIdEqualTo(String value) {
            addCriterion("`member_id` =", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotEqualTo(String value) {
            addCriterion("`member_id` <>", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThan(String value) {
            addCriterion("`member_id` >", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdGreaterThanOrEqualTo(String value) {
            addCriterion("`member_id` >=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThan(String value) {
            addCriterion("`member_id` <", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLessThanOrEqualTo(String value) {
            addCriterion("`member_id` <=", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdLike(String value) {
            addCriterion("`member_id` like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotLike(String value) {
            addCriterion("`member_id` not like", value, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdIn(List<String> values) {
            addCriterion("`member_id` in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotIn(List<String> values) {
            addCriterion("`member_id` not in", values, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdBetween(String value1, String value2) {
            addCriterion("`member_id` between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andMemberIdNotBetween(String value1, String value2) {
            addCriterion("`member_id` not between", value1, value2, "memberId");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("`latitude` is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("`latitude` is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(BigDecimal value) {
            addCriterion("`latitude` =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("`latitude` <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(BigDecimal value) {
            addCriterion("`latitude` >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`latitude` >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(BigDecimal value) {
            addCriterion("`latitude` <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`latitude` <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<BigDecimal> values) {
            addCriterion("`latitude` in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("`latitude` not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`latitude` between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`latitude` not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("`longitude` is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("`longitude` is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(BigDecimal value) {
            addCriterion("`longitude` =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(BigDecimal value) {
            addCriterion("`longitude` <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(BigDecimal value) {
            addCriterion("`longitude` >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`longitude` >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(BigDecimal value) {
            addCriterion("`longitude` <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`longitude` <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<BigDecimal> values) {
            addCriterion("`longitude` in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<BigDecimal> values) {
            addCriterion("`longitude` not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`longitude` between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`longitude` not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNull() {
            addCriterion("`order_status` is null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIsNotNull() {
            addCriterion("`order_status` is not null");
            return (Criteria) this;
        }

        public Criteria andOrderStatusEqualTo(Byte value) {
            addCriterion("`order_status` =", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotEqualTo(Byte value) {
            addCriterion("`order_status` <>", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThan(Byte value) {
            addCriterion("`order_status` >", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`order_status` >=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThan(Byte value) {
            addCriterion("`order_status` <", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`order_status` <=", value, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusIn(List<Byte> values) {
            addCriterion("`order_status` in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotIn(List<Byte> values) {
            addCriterion("`order_status` not in", values, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusBetween(Byte value1, Byte value2) {
            addCriterion("`order_status` between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andOrderStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`order_status` not between", value1, value2, "orderStatus");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("`city_id` is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("`city_id` is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Short value) {
            addCriterion("`city_id` =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Short value) {
            addCriterion("`city_id` <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Short value) {
            addCriterion("`city_id` >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Short value) {
            addCriterion("`city_id` >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Short value) {
            addCriterion("`city_id` <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Short value) {
            addCriterion("`city_id` <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Short> values) {
            addCriterion("`city_id` in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Short> values) {
            addCriterion("`city_id` not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Short value1, Short value2) {
            addCriterion("`city_id` between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Short value1, Short value2) {
            addCriterion("`city_id` not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("`address` is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("`address` is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("`address` =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("`address` <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("`address` >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("`address` >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("`address` <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("`address` <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("`address` like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("`address` not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("`address` in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("`address` not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("`address` between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("`address` not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andCommentStatusIsNull() {
            addCriterion("`comment_status` is null");
            return (Criteria) this;
        }

        public Criteria andCommentStatusIsNotNull() {
            addCriterion("`comment_status` is not null");
            return (Criteria) this;
        }

        public Criteria andCommentStatusEqualTo(Byte value) {
            addCriterion("`comment_status` =", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotEqualTo(Byte value) {
            addCriterion("`comment_status` <>", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusGreaterThan(Byte value) {
            addCriterion("`comment_status` >", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("`comment_status` >=", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusLessThan(Byte value) {
            addCriterion("`comment_status` <", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusLessThanOrEqualTo(Byte value) {
            addCriterion("`comment_status` <=", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusIn(List<Byte> values) {
            addCriterion("`comment_status` in", values, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotIn(List<Byte> values) {
            addCriterion("`comment_status` not in", values, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusBetween(Byte value1, Byte value2) {
            addCriterion("`comment_status` between", value1, value2, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("`comment_status` not between", value1, value2, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNull() {
            addCriterion("`contact_phone` is null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIsNotNull() {
            addCriterion("`contact_phone` is not null");
            return (Criteria) this;
        }

        public Criteria andContactPhoneEqualTo(String value) {
            addCriterion("`contact_phone` =", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotEqualTo(String value) {
            addCriterion("`contact_phone` <>", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThan(String value) {
            addCriterion("`contact_phone` >", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("`contact_phone` >=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThan(String value) {
            addCriterion("`contact_phone` <", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLessThanOrEqualTo(String value) {
            addCriterion("`contact_phone` <=", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneLike(String value) {
            addCriterion("`contact_phone` like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotLike(String value) {
            addCriterion("`contact_phone` not like", value, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneIn(List<String> values) {
            addCriterion("`contact_phone` in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotIn(List<String> values) {
            addCriterion("`contact_phone` not in", values, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneBetween(String value1, String value2) {
            addCriterion("`contact_phone` between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactPhoneNotBetween(String value1, String value2) {
            addCriterion("`contact_phone` not between", value1, value2, "contactPhone");
            return (Criteria) this;
        }

        public Criteria andContactManIsNull() {
            addCriterion("`contact_man` is null");
            return (Criteria) this;
        }

        public Criteria andContactManIsNotNull() {
            addCriterion("`contact_man` is not null");
            return (Criteria) this;
        }

        public Criteria andContactManEqualTo(String value) {
            addCriterion("`contact_man` =", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManNotEqualTo(String value) {
            addCriterion("`contact_man` <>", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManGreaterThan(String value) {
            addCriterion("`contact_man` >", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManGreaterThanOrEqualTo(String value) {
            addCriterion("`contact_man` >=", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManLessThan(String value) {
            addCriterion("`contact_man` <", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManLessThanOrEqualTo(String value) {
            addCriterion("`contact_man` <=", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManLike(String value) {
            addCriterion("`contact_man` like", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManNotLike(String value) {
            addCriterion("`contact_man` not like", value, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManIn(List<String> values) {
            addCriterion("`contact_man` in", values, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManNotIn(List<String> values) {
            addCriterion("`contact_man` not in", values, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManBetween(String value1, String value2) {
            addCriterion("`contact_man` between", value1, value2, "contactMan");
            return (Criteria) this;
        }

        public Criteria andContactManNotBetween(String value1, String value2) {
            addCriterion("`contact_man` not between", value1, value2, "contactMan");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNull() {
            addCriterion("`service_id` is null");
            return (Criteria) this;
        }

        public Criteria andServiceIdIsNotNull() {
            addCriterion("`service_id` is not null");
            return (Criteria) this;
        }

        public Criteria andServiceIdEqualTo(String value) {
            addCriterion("`service_id` =", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotEqualTo(String value) {
            addCriterion("`service_id` <>", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThan(String value) {
            addCriterion("`service_id` >", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdGreaterThanOrEqualTo(String value) {
            addCriterion("`service_id` >=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThan(String value) {
            addCriterion("`service_id` <", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLessThanOrEqualTo(String value) {
            addCriterion("`service_id` <=", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdLike(String value) {
            addCriterion("`service_id` like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotLike(String value) {
            addCriterion("`service_id` not like", value, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdIn(List<String> values) {
            addCriterion("`service_id` in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotIn(List<String> values) {
            addCriterion("`service_id` not in", values, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdBetween(String value1, String value2) {
            addCriterion("`service_id` between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceIdNotBetween(String value1, String value2) {
            addCriterion("`service_id` not between", value1, value2, "serviceId");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNull() {
            addCriterion("`service_name` is null");
            return (Criteria) this;
        }

        public Criteria andServiceNameIsNotNull() {
            addCriterion("`service_name` is not null");
            return (Criteria) this;
        }

        public Criteria andServiceNameEqualTo(String value) {
            addCriterion("`service_name` =", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotEqualTo(String value) {
            addCriterion("`service_name` <>", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThan(String value) {
            addCriterion("`service_name` >", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameGreaterThanOrEqualTo(String value) {
            addCriterion("`service_name` >=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThan(String value) {
            addCriterion("`service_name` <", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLessThanOrEqualTo(String value) {
            addCriterion("`service_name` <=", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameLike(String value) {
            addCriterion("`service_name` like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotLike(String value) {
            addCriterion("`service_name` not like", value, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameIn(List<String> values) {
            addCriterion("`service_name` in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotIn(List<String> values) {
            addCriterion("`service_name` not in", values, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameBetween(String value1, String value2) {
            addCriterion("`service_name` between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andServiceNameNotBetween(String value1, String value2) {
            addCriterion("`service_name` not between", value1, value2, "serviceName");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeIsNull() {
            addCriterion("`journey_fee` is null");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeIsNotNull() {
            addCriterion("`journey_fee` is not null");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeEqualTo(BigDecimal value) {
            addCriterion("`journey_fee` =", value, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeNotEqualTo(BigDecimal value) {
            addCriterion("`journey_fee` <>", value, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeGreaterThan(BigDecimal value) {
            addCriterion("`journey_fee` >", value, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`journey_fee` >=", value, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeLessThan(BigDecimal value) {
            addCriterion("`journey_fee` <", value, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`journey_fee` <=", value, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeIn(List<BigDecimal> values) {
            addCriterion("`journey_fee` in", values, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeNotIn(List<BigDecimal> values) {
            addCriterion("`journey_fee` not in", values, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`journey_fee` between", value1, value2, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andJourneyFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`journey_fee` not between", value1, value2, "journeyFee");
            return (Criteria) this;
        }

        public Criteria andServicePriceIsNull() {
            addCriterion("`service_price` is null");
            return (Criteria) this;
        }

        public Criteria andServicePriceIsNotNull() {
            addCriterion("`service_price` is not null");
            return (Criteria) this;
        }

        public Criteria andServicePriceEqualTo(BigDecimal value) {
            addCriterion("`service_price` =", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotEqualTo(BigDecimal value) {
            addCriterion("`service_price` <>", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceGreaterThan(BigDecimal value) {
            addCriterion("`service_price` >", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`service_price` >=", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLessThan(BigDecimal value) {
            addCriterion("`service_price` <", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`service_price` <=", value, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceIn(List<BigDecimal> values) {
            addCriterion("`service_price` in", values, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotIn(List<BigDecimal> values) {
            addCriterion("`service_price` not in", values, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`service_price` between", value1, value2, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServicePriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`service_price` not between", value1, value2, "servicePrice");
            return (Criteria) this;
        }

        public Criteria andServiceCountIsNull() {
            addCriterion("`service_count` is null");
            return (Criteria) this;
        }

        public Criteria andServiceCountIsNotNull() {
            addCriterion("`service_count` is not null");
            return (Criteria) this;
        }

        public Criteria andServiceCountEqualTo(Integer value) {
            addCriterion("`service_count` =", value, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountNotEqualTo(Integer value) {
            addCriterion("`service_count` <>", value, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountGreaterThan(Integer value) {
            addCriterion("`service_count` >", value, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("`service_count` >=", value, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountLessThan(Integer value) {
            addCriterion("`service_count` <", value, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountLessThanOrEqualTo(Integer value) {
            addCriterion("`service_count` <=", value, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountIn(List<Integer> values) {
            addCriterion("`service_count` in", values, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountNotIn(List<Integer> values) {
            addCriterion("`service_count` not in", values, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountBetween(Integer value1, Integer value2) {
            addCriterion("`service_count` between", value1, value2, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andServiceCountNotBetween(Integer value1, Integer value2) {
            addCriterion("`service_count` not between", value1, value2, "serviceCount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNull() {
            addCriterion("`total_amount` is null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIsNotNull() {
            addCriterion("`total_amount` is not null");
            return (Criteria) this;
        }

        public Criteria andTotalAmountEqualTo(BigDecimal value) {
            addCriterion("`total_amount` =", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotEqualTo(BigDecimal value) {
            addCriterion("`total_amount` <>", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThan(BigDecimal value) {
            addCriterion("`total_amount` >", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("`total_amount` >=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThan(BigDecimal value) {
            addCriterion("`total_amount` <", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("`total_amount` <=", value, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountIn(List<BigDecimal> values) {
            addCriterion("`total_amount` in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotIn(List<BigDecimal> values) {
            addCriterion("`total_amount` not in", values, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`total_amount` between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andTotalAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("`total_amount` not between", value1, value2, "totalAmount");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeIsNull() {
            addCriterion("`book_start_time` is null");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeIsNotNull() {
            addCriterion("`book_start_time` is not null");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeEqualTo(Date value) {
            addCriterion("`book_start_time` =", value, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeNotEqualTo(Date value) {
            addCriterion("`book_start_time` <>", value, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeGreaterThan(Date value) {
            addCriterion("`book_start_time` >", value, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`book_start_time` >=", value, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeLessThan(Date value) {
            addCriterion("`book_start_time` <", value, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("`book_start_time` <=", value, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeIn(List<Date> values) {
            addCriterion("`book_start_time` in", values, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeNotIn(List<Date> values) {
            addCriterion("`book_start_time` not in", values, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeBetween(Date value1, Date value2) {
            addCriterion("`book_start_time` between", value1, value2, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("`book_start_time` not between", value1, value2, "bookStartTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeIsNull() {
            addCriterion("`book_end_time` is null");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeIsNotNull() {
            addCriterion("`book_end_time` is not null");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeEqualTo(Date value) {
            addCriterion("`book_end_time` =", value, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeNotEqualTo(Date value) {
            addCriterion("`book_end_time` <>", value, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeGreaterThan(Date value) {
            addCriterion("`book_end_time` >", value, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`book_end_time` >=", value, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeLessThan(Date value) {
            addCriterion("`book_end_time` <", value, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("`book_end_time` <=", value, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeIn(List<Date> values) {
            addCriterion("`book_end_time` in", values, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeNotIn(List<Date> values) {
            addCriterion("`book_end_time` not in", values, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeBetween(Date value1, Date value2) {
            addCriterion("`book_end_time` between", value1, value2, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andBookEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("`book_end_time` not between", value1, value2, "bookEndTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIsNull() {
            addCriterion("`departure_time` is null");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIsNotNull() {
            addCriterion("`departure_time` is not null");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeEqualTo(Date value) {
            addCriterion("`departure_time` =", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotEqualTo(Date value) {
            addCriterion("`departure_time` <>", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeGreaterThan(Date value) {
            addCriterion("`departure_time` >", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`departure_time` >=", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeLessThan(Date value) {
            addCriterion("`departure_time` <", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeLessThanOrEqualTo(Date value) {
            addCriterion("`departure_time` <=", value, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeIn(List<Date> values) {
            addCriterion("`departure_time` in", values, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotIn(List<Date> values) {
            addCriterion("`departure_time` not in", values, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeBetween(Date value1, Date value2) {
            addCriterion("`departure_time` between", value1, value2, "departureTime");
            return (Criteria) this;
        }

        public Criteria andDepartureTimeNotBetween(Date value1, Date value2) {
            addCriterion("`departure_time` not between", value1, value2, "departureTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeIsNull() {
            addCriterion("`real_serv_start_time` is null");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeIsNotNull() {
            addCriterion("`real_serv_start_time` is not null");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeEqualTo(Date value) {
            addCriterion("`real_serv_start_time` =", value, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeNotEqualTo(Date value) {
            addCriterion("`real_serv_start_time` <>", value, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeGreaterThan(Date value) {
            addCriterion("`real_serv_start_time` >", value, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`real_serv_start_time` >=", value, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeLessThan(Date value) {
            addCriterion("`real_serv_start_time` <", value, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("`real_serv_start_time` <=", value, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeIn(List<Date> values) {
            addCriterion("`real_serv_start_time` in", values, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeNotIn(List<Date> values) {
            addCriterion("`real_serv_start_time` not in", values, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeBetween(Date value1, Date value2) {
            addCriterion("`real_serv_start_time` between", value1, value2, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("`real_serv_start_time` not between", value1, value2, "realServStartTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeIsNull() {
            addCriterion("`real_serv_done_time` is null");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeIsNotNull() {
            addCriterion("`real_serv_done_time` is not null");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeEqualTo(Date value) {
            addCriterion("`real_serv_done_time` =", value, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeNotEqualTo(Date value) {
            addCriterion("`real_serv_done_time` <>", value, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeGreaterThan(Date value) {
            addCriterion("`real_serv_done_time` >", value, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`real_serv_done_time` >=", value, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeLessThan(Date value) {
            addCriterion("`real_serv_done_time` <", value, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeLessThanOrEqualTo(Date value) {
            addCriterion("`real_serv_done_time` <=", value, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeIn(List<Date> values) {
            addCriterion("`real_serv_done_time` in", values, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeNotIn(List<Date> values) {
            addCriterion("`real_serv_done_time` not in", values, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeBetween(Date value1, Date value2) {
            addCriterion("`real_serv_done_time` between", value1, value2, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andRealServDoneTimeNotBetween(Date value1, Date value2) {
            addCriterion("`real_serv_done_time` not between", value1, value2, "realServDoneTime");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIsNull() {
            addCriterion("`cancel_reason` is null");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIsNotNull() {
            addCriterion("`cancel_reason` is not null");
            return (Criteria) this;
        }

        public Criteria andCancelReasonEqualTo(Byte value) {
            addCriterion("`cancel_reason` =", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotEqualTo(Byte value) {
            addCriterion("`cancel_reason` <>", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonGreaterThan(Byte value) {
            addCriterion("`cancel_reason` >", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonGreaterThanOrEqualTo(Byte value) {
            addCriterion("`cancel_reason` >=", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLessThan(Byte value) {
            addCriterion("`cancel_reason` <", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLessThanOrEqualTo(Byte value) {
            addCriterion("`cancel_reason` <=", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIn(List<Byte> values) {
            addCriterion("`cancel_reason` in", values, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotIn(List<Byte> values) {
            addCriterion("`cancel_reason` not in", values, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonBetween(Byte value1, Byte value2) {
            addCriterion("`cancel_reason` between", value1, value2, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotBetween(Byte value1, Byte value2) {
            addCriterion("`cancel_reason` not between", value1, value2, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelTimeIsNull() {
            addCriterion("`cancel_time` is null");
            return (Criteria) this;
        }

        public Criteria andCancelTimeIsNotNull() {
            addCriterion("`cancel_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCancelTimeEqualTo(Date value) {
            addCriterion("`cancel_time` =", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeNotEqualTo(Date value) {
            addCriterion("`cancel_time` <>", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeGreaterThan(Date value) {
            addCriterion("`cancel_time` >", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`cancel_time` >=", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeLessThan(Date value) {
            addCriterion("`cancel_time` <", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeLessThanOrEqualTo(Date value) {
            addCriterion("`cancel_time` <=", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeIn(List<Date> values) {
            addCriterion("`cancel_time` in", values, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeNotIn(List<Date> values) {
            addCriterion("`cancel_time` not in", values, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeBetween(Date value1, Date value2) {
            addCriterion("`cancel_time` between", value1, value2, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeNotBetween(Date value1, Date value2) {
            addCriterion("`cancel_time` not between", value1, value2, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeIsNull() {
            addCriterion("`customer_confirm_time` is null");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeIsNotNull() {
            addCriterion("`customer_confirm_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeEqualTo(Date value) {
            addCriterion("`customer_confirm_time` =", value, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeNotEqualTo(Date value) {
            addCriterion("`customer_confirm_time` <>", value, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeGreaterThan(Date value) {
            addCriterion("`customer_confirm_time` >", value, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`customer_confirm_time` >=", value, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeLessThan(Date value) {
            addCriterion("`customer_confirm_time` <", value, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("`customer_confirm_time` <=", value, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeIn(List<Date> values) {
            addCriterion("`customer_confirm_time` in", values, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeNotIn(List<Date> values) {
            addCriterion("`customer_confirm_time` not in", values, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("`customer_confirm_time` between", value1, value2, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andCustomerConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("`customer_confirm_time` not between", value1, value2, "customerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeIsNull() {
            addCriterion("`provider_confirm_time` is null");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeIsNotNull() {
            addCriterion("`provider_confirm_time` is not null");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeEqualTo(Date value) {
            addCriterion("`provider_confirm_time` =", value, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeNotEqualTo(Date value) {
            addCriterion("`provider_confirm_time` <>", value, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeGreaterThan(Date value) {
            addCriterion("`provider_confirm_time` >", value, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`provider_confirm_time` >=", value, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeLessThan(Date value) {
            addCriterion("`provider_confirm_time` <", value, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeLessThanOrEqualTo(Date value) {
            addCriterion("`provider_confirm_time` <=", value, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeIn(List<Date> values) {
            addCriterion("`provider_confirm_time` in", values, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeNotIn(List<Date> values) {
            addCriterion("`provider_confirm_time` not in", values, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeBetween(Date value1, Date value2) {
            addCriterion("`provider_confirm_time` between", value1, value2, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderConfirmTimeNotBetween(Date value1, Date value2) {
            addCriterion("`provider_confirm_time` not between", value1, value2, "providerConfirmTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeIsNull() {
            addCriterion("`provider_grab_time` is null");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeIsNotNull() {
            addCriterion("`provider_grab_time` is not null");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeEqualTo(Date value) {
            addCriterion("`provider_grab_time` =", value, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeNotEqualTo(Date value) {
            addCriterion("`provider_grab_time` <>", value, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeGreaterThan(Date value) {
            addCriterion("`provider_grab_time` >", value, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`provider_grab_time` >=", value, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeLessThan(Date value) {
            addCriterion("`provider_grab_time` <", value, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeLessThanOrEqualTo(Date value) {
            addCriterion("`provider_grab_time` <=", value, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeIn(List<Date> values) {
            addCriterion("`provider_grab_time` in", values, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeNotIn(List<Date> values) {
            addCriterion("`provider_grab_time` not in", values, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeBetween(Date value1, Date value2) {
            addCriterion("`provider_grab_time` between", value1, value2, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andProviderGrabTimeNotBetween(Date value1, Date value2) {
            addCriterion("`provider_grab_time` not between", value1, value2, "providerGrabTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeIsNull() {
            addCriterion("`state_expire_time` is null");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeIsNotNull() {
            addCriterion("`state_expire_time` is not null");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeEqualTo(Date value) {
            addCriterion("`state_expire_time` =", value, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeNotEqualTo(Date value) {
            addCriterion("`state_expire_time` <>", value, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeGreaterThan(Date value) {
            addCriterion("`state_expire_time` >", value, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`state_expire_time` >=", value, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeLessThan(Date value) {
            addCriterion("`state_expire_time` <", value, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("`state_expire_time` <=", value, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeIn(List<Date> values) {
            addCriterion("`state_expire_time` in", values, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeNotIn(List<Date> values) {
            addCriterion("`state_expire_time` not in", values, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeBetween(Date value1, Date value2) {
            addCriterion("`state_expire_time` between", value1, value2, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andStateExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("`state_expire_time` not between", value1, value2, "stateExpireTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNull() {
            addCriterion("`create_by` is null");
            return (Criteria) this;
        }

        public Criteria andCreateByIsNotNull() {
            addCriterion("`create_by` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateByEqualTo(String value) {
            addCriterion("`create_by` =", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotEqualTo(String value) {
            addCriterion("`create_by` <>", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThan(String value) {
            addCriterion("`create_by` >", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByGreaterThanOrEqualTo(String value) {
            addCriterion("`create_by` >=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThan(String value) {
            addCriterion("`create_by` <", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLessThanOrEqualTo(String value) {
            addCriterion("`create_by` <=", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByLike(String value) {
            addCriterion("`create_by` like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotLike(String value) {
            addCriterion("`create_by` not like", value, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByIn(List<String> values) {
            addCriterion("`create_by` in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotIn(List<String> values) {
            addCriterion("`create_by` not in", values, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByBetween(String value1, String value2) {
            addCriterion("`create_by` between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andCreateByNotBetween(String value1, String value2) {
            addCriterion("`create_by` not between", value1, value2, "createBy");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("`update_time` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("`update_time` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("`update_time` =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("`update_time` <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("`update_time` >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("`update_time` >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("`update_time` <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("`update_time` <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("`update_time` in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("`update_time` not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("`update_time` between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("`update_time` not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNull() {
            addCriterion("`update_by` is null");
            return (Criteria) this;
        }

        public Criteria andUpdateByIsNotNull() {
            addCriterion("`update_by` is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateByEqualTo(String value) {
            addCriterion("`update_by` =", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotEqualTo(String value) {
            addCriterion("`update_by` <>", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThan(String value) {
            addCriterion("`update_by` >", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByGreaterThanOrEqualTo(String value) {
            addCriterion("`update_by` >=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThan(String value) {
            addCriterion("`update_by` <", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLessThanOrEqualTo(String value) {
            addCriterion("`update_by` <=", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByLike(String value) {
            addCriterion("`update_by` like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotLike(String value) {
            addCriterion("`update_by` not like", value, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByIn(List<String> values) {
            addCriterion("`update_by` in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotIn(List<String> values) {
            addCriterion("`update_by` not in", values, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByBetween(String value1, String value2) {
            addCriterion("`update_by` between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andUpdateByNotBetween(String value1, String value2) {
            addCriterion("`update_by` not between", value1, value2, "updateBy");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("`version` is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("`version` is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Integer value) {
            addCriterion("`version` =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Integer value) {
            addCriterion("`version` <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Integer value) {
            addCriterion("`version` >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
            addCriterion("`version` >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Integer value) {
            addCriterion("`version` <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Integer value) {
            addCriterion("`version` <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Integer> values) {
            addCriterion("`version` in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Integer> values) {
            addCriterion("`version` not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Integer value1, Integer value2) {
            addCriterion("`version` between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Integer value1, Integer value2) {
            addCriterion("`version` not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_info
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}