package com.o2o.massage.dao.entity;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table payment_record
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class PaymentRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   支付单ID，外键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.payment_order_id
     *
     * @mbg.generated
     */
    private Long paymentOrderId;

    /**
     * Database Column Remarks:
     *   支付单号/支付交易号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.pay_trade_no
     *
     * @mbg.generated
     */
    private String payTradeNo;

    /**
     * Database Column Remarks:
     *   用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.customer_user_id
     *
     * @mbg.generated
     */
    private String customerUserId;

    /**
     * Database Column Remarks:
     *   用户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.customer_name
     *
     * @mbg.generated
     */
    private String customerName;

    /**
     * Database Column Remarks:
     *   业务订单号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.biz_order_no
     *
     * @mbg.generated
     */
    private String bizOrderNo;

    /**
     * Database Column Remarks:
     *   支付记录交易号/支付流水号(支付系统生成，唯一)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.transaction_no
     *
     * @mbg.generated
     */
    private String transactionNo;

    /**
     * Database Column Remarks:
     *   支付状态(100->未支付，101->支付成功)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.pay_status
     *
     * @mbg.generated
     */
    private Byte payStatus;

    /**
     * Database Column Remarks:
     *   支付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.pay_amount
     *
     * @mbg.generated
     */
    private BigDecimal payAmount;

    /**
     * Database Column Remarks:
     *   支付手续费费率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.fee_rate
     *
     * @mbg.generated
     */
    private BigDecimal feeRate;

    /**
     * Database Column Remarks:
     *   发送至三方的交易流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     * Database Column Remarks:
     *   三方交易流水号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.out_transaction_no
     *
     * @mbg.generated
     */
    private String outTransactionNo;

    /**
     * Database Column Remarks:
     *   支付渠道编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.pay_way_no
     *
     * @mbg.generated
     */
    private Byte payWayNo;

    /**
     * Database Column Remarks:
     *   支付渠道名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.pay_way_name
     *
     * @mbg.generated
     */
    private String payWayName;

    /**
     * Database Column Remarks:
     *   支付完成时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.paid_time
     *
     * @mbg.generated
     */
    private Date paidTime;

    /**
     * Database Column Remarks:
     *   支付凭证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.payment_sign
     *
     * @mbg.generated
     */
    private String paymentSign;

    /**
     * Database Column Remarks:
     *   后台异步通知url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.notify_url
     *
     * @mbg.generated
     */
    private String notifyUrl;

    /**
     * Database Column Remarks:
     *   是否有退款
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.has_refund
     *
     * @mbg.generated
     */
    private Byte hasRefund;

    /**
     * Database Column Remarks:
     *   退款金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.refund_amount
     *
     * @mbg.generated
     */
    private BigDecimal refundAmount;

    /**
     * Database Column Remarks:
     *   创建者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   最后修改者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.update_by
     *
     * @mbg.generated
     */
    private String updateBy;

    /**
     * Database Column Remarks:
     *   最后修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   版本-乐观锁
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column payment_record.version
     *
     * @mbg.generated
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.id
     *
     * @return the value of payment_record.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.id
     *
     * @param id the value for payment_record.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.payment_order_id
     *
     * @return the value of payment_record.payment_order_id
     *
     * @mbg.generated
     */
    public Long getPaymentOrderId() {
        return paymentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.payment_order_id
     *
     * @param paymentOrderId the value for payment_record.payment_order_id
     *
     * @mbg.generated
     */
    public void setPaymentOrderId(Long paymentOrderId) {
        this.paymentOrderId = paymentOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.pay_trade_no
     *
     * @return the value of payment_record.pay_trade_no
     *
     * @mbg.generated
     */
    public String getPayTradeNo() {
        return payTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.pay_trade_no
     *
     * @param payTradeNo the value for payment_record.pay_trade_no
     *
     * @mbg.generated
     */
    public void setPayTradeNo(String payTradeNo) {
        this.payTradeNo = payTradeNo == null ? null : payTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.customer_user_id
     *
     * @return the value of payment_record.customer_user_id
     *
     * @mbg.generated
     */
    public String getCustomerUserId() {
        return customerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.customer_user_id
     *
     * @param customerUserId the value for payment_record.customer_user_id
     *
     * @mbg.generated
     */
    public void setCustomerUserId(String customerUserId) {
        this.customerUserId = customerUserId == null ? null : customerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.customer_name
     *
     * @return the value of payment_record.customer_name
     *
     * @mbg.generated
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.customer_name
     *
     * @param customerName the value for payment_record.customer_name
     *
     * @mbg.generated
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName == null ? null : customerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.biz_order_no
     *
     * @return the value of payment_record.biz_order_no
     *
     * @mbg.generated
     */
    public String getBizOrderNo() {
        return bizOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.biz_order_no
     *
     * @param bizOrderNo the value for payment_record.biz_order_no
     *
     * @mbg.generated
     */
    public void setBizOrderNo(String bizOrderNo) {
        this.bizOrderNo = bizOrderNo == null ? null : bizOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.transaction_no
     *
     * @return the value of payment_record.transaction_no
     *
     * @mbg.generated
     */
    public String getTransactionNo() {
        return transactionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.transaction_no
     *
     * @param transactionNo the value for payment_record.transaction_no
     *
     * @mbg.generated
     */
    public void setTransactionNo(String transactionNo) {
        this.transactionNo = transactionNo == null ? null : transactionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.pay_status
     *
     * @return the value of payment_record.pay_status
     *
     * @mbg.generated
     */
    public Byte getPayStatus() {
        return payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.pay_status
     *
     * @param payStatus the value for payment_record.pay_status
     *
     * @mbg.generated
     */
    public void setPayStatus(Byte payStatus) {
        this.payStatus = payStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.pay_amount
     *
     * @return the value of payment_record.pay_amount
     *
     * @mbg.generated
     */
    public BigDecimal getPayAmount() {
        return payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.pay_amount
     *
     * @param payAmount the value for payment_record.pay_amount
     *
     * @mbg.generated
     */
    public void setPayAmount(BigDecimal payAmount) {
        this.payAmount = payAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.fee_rate
     *
     * @return the value of payment_record.fee_rate
     *
     * @mbg.generated
     */
    public BigDecimal getFeeRate() {
        return feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.fee_rate
     *
     * @param feeRate the value for payment_record.fee_rate
     *
     * @mbg.generated
     */
    public void setFeeRate(BigDecimal feeRate) {
        this.feeRate = feeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.out_trade_no
     *
     * @return the value of payment_record.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.out_trade_no
     *
     * @param outTradeNo the value for payment_record.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.out_transaction_no
     *
     * @return the value of payment_record.out_transaction_no
     *
     * @mbg.generated
     */
    public String getOutTransactionNo() {
        return outTransactionNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.out_transaction_no
     *
     * @param outTransactionNo the value for payment_record.out_transaction_no
     *
     * @mbg.generated
     */
    public void setOutTransactionNo(String outTransactionNo) {
        this.outTransactionNo = outTransactionNo == null ? null : outTransactionNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.pay_way_no
     *
     * @return the value of payment_record.pay_way_no
     *
     * @mbg.generated
     */
    public Byte getPayWayNo() {
        return payWayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.pay_way_no
     *
     * @param payWayNo the value for payment_record.pay_way_no
     *
     * @mbg.generated
     */
    public void setPayWayNo(Byte payWayNo) {
        this.payWayNo = payWayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.pay_way_name
     *
     * @return the value of payment_record.pay_way_name
     *
     * @mbg.generated
     */
    public String getPayWayName() {
        return payWayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.pay_way_name
     *
     * @param payWayName the value for payment_record.pay_way_name
     *
     * @mbg.generated
     */
    public void setPayWayName(String payWayName) {
        this.payWayName = payWayName == null ? null : payWayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.paid_time
     *
     * @return the value of payment_record.paid_time
     *
     * @mbg.generated
     */
    public Date getPaidTime() {
        return paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.paid_time
     *
     * @param paidTime the value for payment_record.paid_time
     *
     * @mbg.generated
     */
    public void setPaidTime(Date paidTime) {
        this.paidTime = paidTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.payment_sign
     *
     * @return the value of payment_record.payment_sign
     *
     * @mbg.generated
     */
    public String getPaymentSign() {
        return paymentSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.payment_sign
     *
     * @param paymentSign the value for payment_record.payment_sign
     *
     * @mbg.generated
     */
    public void setPaymentSign(String paymentSign) {
        this.paymentSign = paymentSign == null ? null : paymentSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.notify_url
     *
     * @return the value of payment_record.notify_url
     *
     * @mbg.generated
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.notify_url
     *
     * @param notifyUrl the value for payment_record.notify_url
     *
     * @mbg.generated
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl == null ? null : notifyUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.has_refund
     *
     * @return the value of payment_record.has_refund
     *
     * @mbg.generated
     */
    public Byte getHasRefund() {
        return hasRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.has_refund
     *
     * @param hasRefund the value for payment_record.has_refund
     *
     * @mbg.generated
     */
    public void setHasRefund(Byte hasRefund) {
        this.hasRefund = hasRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.refund_amount
     *
     * @return the value of payment_record.refund_amount
     *
     * @mbg.generated
     */
    public BigDecimal getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.refund_amount
     *
     * @param refundAmount the value for payment_record.refund_amount
     *
     * @mbg.generated
     */
    public void setRefundAmount(BigDecimal refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.create_by
     *
     * @return the value of payment_record.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.create_by
     *
     * @param createBy the value for payment_record.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.create_time
     *
     * @return the value of payment_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.create_time
     *
     * @param createTime the value for payment_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.update_by
     *
     * @return the value of payment_record.update_by
     *
     * @mbg.generated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.update_by
     *
     * @param updateBy the value for payment_record.update_by
     *
     * @mbg.generated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.update_time
     *
     * @return the value of payment_record.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.update_time
     *
     * @param updateTime the value for payment_record.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column payment_record.version
     *
     * @return the value of payment_record.version
     *
     * @mbg.generated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column payment_record.version
     *
     * @param version the value for payment_record.version
     *
     * @mbg.generated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}