package com.o2o.massage.dao.mapper;

import com.o2o.massage.dao.entity.FamilyMember;
import com.o2o.massage.dao.entity.FamilyMemberExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface FamilyMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    long countByExample(FamilyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    int insert(FamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    int insertSelective(FamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    List<FamilyMember> selectByExample(FamilyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    FamilyMember selectByPrimaryKey(String memberId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FamilyMember record, @Param("example") FamilyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FamilyMember record, @Param("example") FamilyMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FamilyMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table family_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FamilyMember record);
}