package com.o2o.massage.dao.mapper;

import com.o2o.massage.dao.entity.PaymentRecord;
import com.o2o.massage.dao.entity.PaymentRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    long countByExample(PaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    int insert(PaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    int insertSelective(PaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    List<PaymentRecord> selectByExample(PaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    PaymentRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PaymentRecord record, @Param("example") PaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PaymentRecord record, @Param("example") PaymentRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PaymentRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PaymentRecord record);
}