package com.o2o.massage.dao.mapper;

import com.o2o.massage.dao.entity.ProviderCertificationInfo;
import com.o2o.massage.dao.entity.ProviderCertificationInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProviderCertificationInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    long countByExample(ProviderCertificationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    int insert(ProviderCertificationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    int insertSelective(ProviderCertificationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    List<ProviderCertificationInfo> selectByExample(ProviderCertificationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    ProviderCertificationInfo selectByPrimaryKey(Long certificationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProviderCertificationInfo record, @Param("example") ProviderCertificationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProviderCertificationInfo record, @Param("example") ProviderCertificationInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProviderCertificationInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_certification_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProviderCertificationInfo record);
}