package com.o2o.massage.dao.mapper;

import com.o2o.massage.dao.entity.ProviderInfo;
import com.o2o.massage.dao.entity.ProviderInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProviderInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    long countByExample(ProviderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    int insert(ProviderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    int insertSelective(ProviderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    List<ProviderInfo> selectByExample(ProviderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    ProviderInfo selectByPrimaryKey(Long providerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProviderInfo record, @Param("example") ProviderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProviderInfo record, @Param("example") ProviderInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProviderInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProviderInfo record);
}