package com.o2o.massage.dao.mapper;

import com.o2o.massage.dao.entity.ProviderServiceStatic;
import com.o2o.massage.dao.entity.ProviderServiceStaticExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProviderServiceStaticMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_service_static
     *
     * @mbg.generated
     */
    long countByExample(ProviderServiceStaticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_service_static
     *
     * @mbg.generated
     */
    int insert(ProviderServiceStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_service_static
     *
     * @mbg.generated
     */
    int insertSelective(ProviderServiceStatic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_service_static
     *
     * @mbg.generated
     */
    List<ProviderServiceStatic> selectByExample(ProviderServiceStaticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_service_static
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProviderServiceStatic record, @Param("example") ProviderServiceStaticExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_service_static
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProviderServiceStatic record, @Param("example") ProviderServiceStaticExample example);
}