package com.o2o.massage.dao.mapper;

import com.o2o.massage.dao.entity.ServiceDef;
import com.o2o.massage.dao.entity.ServiceInfo;
import com.o2o.massage.dao.entity.ServiceInfoExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ServiceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    long countByExample(ServiceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    int insert(ServiceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    int insertSelective(ServiceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    List<ServiceInfo> selectByExample(ServiceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    ServiceInfo selectByPrimaryKey(String serviceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ServiceInfo record, @Param("example") ServiceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ServiceInfo record, @Param("example") ServiceInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ServiceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table service_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ServiceInfo record);

    List<ServiceDef> getDefaultServiceDefs(String userId);

    ServiceDef getService(@Param("userId") String userId, @Param("serviceId") String serviceId);
}